apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pvc
        - name: certs
          secret:
            secretName: minio-tls
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-09-16T01-01-47Z
          args:
            - server
            - /data
            - --console-address
            - ":9001"
            - --certs-dir
            - /certs
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-password
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: storage
              mountPath: "/data"
            - name: certs
              mountPath: "/certs"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: api
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: api
            periodSeconds: 20