---
apiVersion: v1
kind: Namespace
metadata:
  name: minio

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vm-k8s-demo-01-worker-01
                - vm-k8s-demo-01-worker-02
                - vm-k8s-demo-01-worker-03

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-tls
  namespace: minio
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDazCCAlOgAwIBAgIUXPo4OmamABnXOLECO1H58jqwUV4wDQYJKoZIhvcNAQEL
    BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMzA5MTcwMjU1MzhaFw0yNDA5
    MTYwMjU1MzhaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
    HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQC3pP7BbWC5OLkYNBQ5u/4w38H8yAqCqHujSVu+Mfyl
    K1QcVjTd2LwOJoB2WfKeBotl3N8TtRZ+iD8lhT9lXfRBxS2gOSAMC5N2sG6nTX++
    qocxB+PU/4e4uLJMY/eWoVsASpyj8hvDOX3NWPwOkwF6Xyrl+1hRjVV/EjWIkKEe
    t6JQdXs/qpX1+uuX8zj2ZgnuJvVl+E/Fb3sGqrTYyAdGqCz743zcUXV3HWVMb/uu
    9YTSumHV/QCgq0l6y+Cva3Yr7X3xGXVsVo4JVV+D/bCnCWzkNBrVW2VwTDWpU4F4
    DcavyuN45fMCyX0/+zSwwrh4DEPwvNWqOkAZq/j4OsnvAgMBAAGjUzBRMB0GA1Ud
    DgQWBBR08IulNcmDh/eSR7q6vz12YxKO7jAfBgNVHSMEGDAWgBR08IulNcmDh/eS
    R7q6vz12YxKO7jAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAL
    USAvsJaRRvhKWXlZ2l+0a9WUNtH4vQ6YohWL/mGV3pD3vDg44xNwQMjMqhzy9ht9
    DJKPRdz8upx1vFZELYn2XTJVcutP3UcUU+cA8c/qo+yOJ2pJ5FrV66NOH9rNSXhA
    b7XR0kqAHwWC0uLlbGFZaWF7uXVNrnGGWhjpZEQWdSbk5KR76R6C6NSr1B5tAWV9
    IbFNZHDLzzxo3CY6gshfrKuXc2kmNbYsPZ15RqQzq+DyF0hAzcg6YXV3jPtQI4N8
    /L9tDfFyQM9bWxcaqf5cHCcv31qEMi06Y+9mIiqDZ4zTOXkFDGVhJwY/GKZB9qXZ
    nWP7bPpmvnAvfX70n9XR
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC3pP7BbWC5OLkY
    NBQ5u/4w38H8yAqCqHujSVu+MfylK1QcVjTd2LwOJoB2WfKeBotl3N8TtRZ+iD8l
    hT9lXfRBxS2gOSAMC5N2sG6nTX++qocxB+PU/4e4uLJMY/eWoVsASpyj8hvDOX3N
    WPwOkwF6Xyrl+1hRjVV/EjWIkKEet6JQdXs/qpX1+uuX8zj2ZgnuJvVl+E/Fb3sG
    qrTYyAdGqCz743zcUXV3HWVMb/uu9YTSumHV/QCgq0l6y+Cva3Yr7X3xGXVsVo4J
    VV+D/bCnCWzkNBrVW2VwTDWpU4F4DcavyuN45fMCyX0/+zSwwrh4DEPwvNWqOkAZ
    q/j4OsnvAgMBAAECggEAQKpDWq6gBYGYX4wJ0y7ECfvgXA7gVvYXHjBumrDYlVlj
    hC3F7fTXF/+/mCfiEwGdGTTlvqf/5EvIwm5jRaeYIz+RsLZGV0j5QsWh7+BVwLSY
    rFY3NTDA3X9rBVEIiLyqiGZ1DKqoM24GTN6qNp8yzj/Rb7kf8sJeM5n8RFDvRLUH
    K2HCGEiG/c2w0B+oIAaLTkjKWLXVPhELY//Jz1nETp0hVDbsmmI96QYG1gNGFD1o
    m0HKI3P7nPfWgXmZZXIvSDOQPlVLtVJ64YI7ojJzCTKOMVpTkl3SizGXnA7hkXHm
    W6JRFbWlWXK6jYHH8eX3ajyK5P3V06OVjfADKmHs4QKBgQDrZ2y3M6SjNFhWLLVE
    Zzeu4gxgLp8l8wkHo+l9QqzAz23u9PsEt8dLTm6SFbPxJrVUu5NJWHlg05a4eIGR
    eo7T9OVOEi4ESDPpS7FfLGvUYc/h1xdHOICZe7FJujhVDQPNEFhpnhEMCuPe4BOR
    vS8RMRjj6Dj/SCKDjE0MCZWwWQKBgQDHjM9dFnv2/lTNovOPLvxdWm2E5qBodLO7
    oBjA1XC/pIoVjwRFwORMpS9YWRJh7b3+XuRVRiSJ9b6nV+BX4xSa2nK8lbSzaLz9
    VkKrv3kFfJzSEXbWUG/Q1Jt47b3nRxDOc5rqy1QJUKdh1zOjfZ60oZ0SOktDRH+H
    n4e8XLMthwKBgB2C+9NlX+iJqeNOLpBJZPiKxUaqbPBDz3hdZsW3PBTXmK4jtzZa
    CeXNElZYPWGlNmqW4Doy0kj/9h2r9V6MO90Afjzxjd/4UXqWD+a4eKmEQVyWi4tv
    IuLcZRlBCcGYDlzTZvN0YYOiZu8MIxrOYQUPJ5gAPT3BoIYBNHoXhZOBAoGBAIxS
    xtNUNlIxEAwxHvl0r4IK/60e2GNBXhpXGKKlrMyi80dAb6UT4QRpOl4QCbGGuvjm
    8Hd3y9J5p81FtzRbwgLWp5L3vKNEt+l6uUUGbubvcj5bNSuF5M8QVt+zdldCCU0r
    k19t2jyHkESLAiXTCBnXNKsfUZcY0zrBUfGvMd6fAoGBAOgxFCrHDBSU8fmLnxc5
    OdC7WrTk2+PSVqMc5Z3qxnvr0SSmcWx1UPjZBX6LtoDvDXGM5fGTR5xN8sXEbTPf
    4Vu+kSe5CKaDfnMxmXZJhxYNIu96QJNujEg8NMPYvKvUPFZl/SCOCM9e5VKxw42T
    +swQ0MHKN2ASZSXwbatCQgc6
    -----END PRIVATE KEY-----

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pvc
        - name: certs
          secret:
            secretName: minio-tls
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-09-16T01-01-47Z
          args:
            - server
            - /data
            - --console-address
            - ":9001"
            - --certs-dir
            - /certs
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-password
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: storage
              mountPath: "/data"
            - name: certs
              mountPath: "/certs"

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 9000
      name: api
    - port: 9001
      targetPort: 9001
      name: console
  selector:
    app: minio

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - minio.fallah.ai
      secretName: minio-tls
  rules:
    - host: minio.fallah.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 443
          - path: /console
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001